
calc: calc.c ./headers/types.h ./headers/test.h ./headers/calc.h
	gcc calc.c -Wall -o calc.out

run: calc.c ./headers/types.h ./headers/test.h ./headers/calc.h
	gcc calc.c -Wall -o calc.out && ./calc.out

debug: calc.c ./headers/types.h ./headers/test.h ./headers/calc.h
	gcc calc.c -Wall -g -o debug.out